# Generated by Django 4.2.20 on 2025-05-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cntrydetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='common_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='official_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
